class Emojis:

    star = "⭐"
    star1 = "✨"
    check = "✅"
    cross = "❌"
    warning = "⚠️"
    error = "❗"
    four_clover = "🍀"
    phone = "📞"
    phone1 = "📱"
    script = "📜"
    voice = "🗣️"
    digits = "🔢"
    person = "👤"
    mask = "🎭"
    human = "🧑‍🦰"
    lock = "🔐"
    recycle = "🔄"
    globe = "🌐"
    key = "🔑"
